### ISSUE TITLE
Working Example Needed

### ISSUE THREAD

**Issue by beeeku** [weilandia/use-action-cable#1]
Hi Nick ! Thank you for creating this library ! I tried to implement this inside a react on rails app but couldn't figure out how to do it . It always had some or other error .
If it's possible can you provide a working example with hooks . 
Thanks
Bikash

**Comment by weilandia** [comment]
Hey Bikash!  Thanks for the issue.  I've added an example app here: https://github.com/weilandia/use_action_cable_example

Also, I've fixed a bug that might have been causing issues for you. There was a race condition between the React app loading and the websocket connection being established, which I didn't notice because I've only used this on larger apps where the React app always loaded second. 

Lmk if you run into any other issues!

**Comment by weilandia** [comment]
No response, closing for cleanup.  Feel free to reopen.
